# install icon
install_data(
  'PdfToCbr.svg',
  install_dir: join_paths(
        get_option('datadir'), 
        'icons', 
        'hicolor',
        'scalable',
        'apps',
    ),
)

# install launcher
install_data(
  'PdfToCbr.desktop',
  install_dir: join_paths(
        get_option('datadir'), 
        'applications',
    ),
)